name: freetogame_app
description: "A new Flutter project."
# Deskripsi singkat tentang proyek Flutter yang sedang dibuat.

publish_to: "none" # Baris ini mencegah paket untuk dipublikasikan secara tidak sengaja ke pub.dev menggunakan `flutter pub publish`.

flutter_native_splash:
  color: "#42a5f5"
  image: assets/logo.png
# Konfigurasi untuk splash screen yang menampilkan gambar logo saat aplikasi memulai.

version: 1.0.0+1
# Versi aplikasi dengan format semver (major.minor.patch+build).

environment:
  sdk: ">=3.3.1 <4.0.0"
# Versi SDK minimum yang dibutuhkan untuk menjalankan aplikasi Flutter.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  flutter_native_splash: ^2.4.0
# Daftar dependensi yang dibutuhkan aplikasi, seperti Flutter SDK, HTTP client, Firebase Core, Firebase Auth, dan Cloud Firestore.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
# Daftar dependensi pengembangan untuk testing dan linter Flutter.

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
# Konfigurasi untuk menggunakan Material Design dan menambahkan asset gambar logo ke aplikasi.

# Untuk informasi tentang bagian Dart generik dari file ini, lihat halaman berikut: https://dart.dev/tools/pub/pubspec
